# REDIS CACHE DATA BASES
# LOCAL:         0
# DEV:           5
# QA             4
# DEMO:          7
# PROD:          6
# DEV-CLIENTE:   8
# FARGATE-TESTE: 9
server:
  port: ${PORT:${SERVER_PORT:0}}

info:
  id: ${spring.application.name}

management:
  health:
    elasticsearch:
      enabled: false
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
         
ribbon:
  ReadTimeout: 60000

eureka:
  instance:
    hostname: localhost
    port: 8890
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8890/eureka/
      healthcheck:
        enabled: true

#Security Properties
keycloak:
  realm:
    uri: https://iam.dev.apollusehs.com.br/auth/realms/apollus

#Spring Security OAuth2 properties
security:
  oauth2:
    resource:
      id: account
      token-info-uri: ${keycloak.realm.uri}/protocol/openid-connect/token/introspect
      user-info-uri: ${keycloak.realm.uri}/protocol/openid-connect/userinfo
      jwt:
        key-value: |
          -----BEGIN PUBLIC KEY-----
          MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEApYg7AovvI3SDuRoxzrx6U0JT484xpkDijC8XHGtd7onXJADrAB4vTzB4A3ZLncRBRR8GUbiJdd8dqES+182Av3lGgxmLurNsuLPzPIRagUHvomQrK95QRos9uv0FQVA69uwVpYZPmhTVlUhymoiWvp5kXbgzFb1ZxXAuLZPCx8+p/Y861yp+UCmAXkfBxDeXvzGzsp8r6to5E8QtNMYLncjWBoQXlk4CCo0zHKZ74DLGJt7iG/oQdfi0spGDMHyKRFHN8FKD2Cu+ykrl4Y2DHQRA88hmdWV6+weo8zk/3Uir2JvA7MusK3QIpAN6tgarHmgHMLpqPOnZtXkO394BMQIDAQAB
          -----END PUBLIC KEY-----
      
# CONFG DO SPRING BOOT
spring:
  redis:
    host: localhost
    port: 6379
    database: 0
  datasource:
    platform: postgres
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/apollus-saas
    username: postgres
    password: root
    type: com.zaxxer.hikari.HikariDataSource
    initialSize: 1
    min-idle: 0
    max-idle: 0
    max-active: 5
    testOnBorrow: true
    validationQuery: SELECT 1
    timeBetweenEvictionRunsMillis: 34000
    minEvictableIdleTimeMillis: 55000
    removeAbandoned: true
    hikari:
      minimum-idle: 0
      maximum-pool-size: 5
      connection-timeout: 60000
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        create_empty_composites:
          enabled: true
        jdbc:
          batch_size: 10
          lob:
            non_contextual_creation: true
        format_sql: false
        multiTenancy: DATABASE
        multi_tenant_connection_provider: br.com.apollus.core.multitenant.DataSourceBasedMultiTenantConnectionProviderImpl
        tenant_identifier_resolver: br.com.apollus.core.multitenant.TenantIdentifierResolver
  mail:
    default-encoding: UTF-8
    from: apollus@apollusehs.com.br
    host: email-smtp.us-east-1.amazonaws.com
    username: AKIAIYS7CJW74YYFUDOQ
    password: ArbNQ1fQSEkzJxr+DEskry/onShsbfM62BgXFdU3lCYn
    port: 465
    protocol: smtps
    properties.mail.smtp:
      starttls.enable: true
      starttls.required: true
      ssl.enable: true
    properties.mail.smtps:
      auth: true  
  http:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

# SISTEMA APOLLUS - dados entre perfis podem mudar. alterar posterieormente para profiles
apollus:
  ldap:
    url: ldap://ldap.dev.apollusehs.com.br
    admin_dn: cn=admin,dc=dev,dc=apollusehs,dc=com,dc=br
    password: U3BCxQceQWHW4C3
    domain_base: ou=people,dc=dev,dc=apollusehs,dc=com,dc=br
  aws:
    lambda:
      relatorio: https://ekgy409rkk.execute-api.us-east-1.amazonaws.com/dev
      usuario: AKIAXGIINMWW67OOHBGK
      senha: Stiv82QabcOxTUnA/llTo647me4BsAqejSPYd/6X
      regiao: us-east-1
      account: 494475765165
  esocial:
    url: http://localhost:7000/
    ambiente: 2
  origins: 127.0.0.1
  highcharts: http://highchart-utils.apollusehs.com.br
  # DADOS DE CACHE DO APOLLUS (REDIS)
  cache:
    relatorio: 
       url: redis.dev.apollusehs.com.br
       port: 9736
       database: 10
  # SISTEMA
  profile: DEV
  # AWS S3
  uploads:
    tipo: s3
    pasta:
      logo: public/logos/
      publica: public/uploads/
      temporaria: tmp/1/
    bucket:
      privado: apollus-uploads-dev
      publico: apollus-public-dev
      relatorio: apollus-relatorio-dev
    acesso:
      usuario: AKIAXGIINMWWUR6DGK7P
      senha: jvyLjpD3s0jgC7qYoJ3eYT/pXeFn/22ReK7GY0TH

  # multi tenant
  tenant:
    habilitado: true
    datasource:
      initialSize: 0
      maxIdle: 5
      minIdle: 0
      maxActive: 15
      testOnBorrow: true
      validationQuery: SELECT 1
      removeAbandoned: true
      validationTimeout: 30000
      timeBetweenEvictionRunsMillis: 34000
      minEvictableIdleTimeMillis: 55000
      maxLifetime: 60000
      idleTimeout: 60000
      connectionTimeout: 60000
  elastic:
    cluster_name: elk-dev-apollus
    host: elk-logstash.dev.apollusehs.com.br
    port: 9200
    auditoria:
      index: i_local_auditoria
    requisicao:
      index: i_local_requisicao
    acesso:
      index: i_local_acesso
    email:
      index: i_local_email
    notificacao:
      index: i_notificacao
    log:
      index: i_local_log
    esocial:
      index: i_local_esocial

feign:
  client:
    config:
      default:
        connectTimeout: 30000
        readTimeout: 30000
        loggerLevel: basic

cloud:
  aws:
    credentials:
      accessKey: AKIAIXYQVLBDO4777QLQ
      secretKey: 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
    region:
      static: us-east-1
    stack:
      auto: false

svc:
  esocial:
    port: http://localhost:7000/esocial

logging:
   level:
      io.swagger.models.parameters.AbstractSerializableParameter: error
      net.logstash.logback.appender.LogstashTcpSocketAppender: error
   logstash:
      host: elk-logstash.dev.apollusehs.com.br
