# REDIS CACHE DATA BASES
# LOCAL:         0
# DEV:           5
# QA             4
# DEMO:          7
# PROD:          6
# DEV-CLIENTE:   8
# FARGATE-TESTE: 9
server:
  port: ${PORT:${SERVER_PORT:0}}

info:
  id: ${spring.application.name}
